In [1]:
from src.data_reader import DataReader
from src.constant import *
import matplotlib.pyplot as plt
import numpy as np
from src.datasets.dataset import Dataset
from src.models.itemknn import ItemKNN
import pandas as pd

In [2]:
dataset = Dataset()

In [3]:
lead_data = dataset.get_test_leaderboard_sessions()

In [4]:
model = ItemKNN(dataset, topk=1000)

In [5]:
full_data = dataset.get_train_sessions()

In [6]:
model.compute_similarity_matrix(full_data)

Done: 100%|██████████| 23691/23691 [00:00<00:00, 31467.95it/s]


In [7]:
recs = model.recommend(
    interactions=lead_data,
    remove_seen=True,
    cutoff=100,
    leaderboard=True
)

Considering white list items...


In [8]:
dataset.create_submission(recs, sub_name="ItemKNN")

Submission with name: ItemKNN created succesfully!


In [9]:
a = np.array([[1,2,3], [4,5,6]])

In [10]:
a[:, [0,1]]=0

In [11]:
a

array([[0, 0, 3],
       [0, 0, 6]])

In [12]:
mask_array = np.ones(a.shape[1], dtype=bool)

In [13]:
mask_array[[1,2]] = False

In [14]:
mask_array

array([ True, False, False])

In [15]:
a[:, mask_array] = 50

In [16]:
a

array([[50,  0,  3],
       [50,  0,  6]])