In [3]:
from src.data_reader import DataReader
from src.constant import *
import matplotlib.pyplot as plt
import numpy as np
from src.datasets.dataset import Dataset
from src.models.itemknn.itemknn import ItemKNN
import pandas as pd
from src.evaluation import compute_mrr

In [4]:
dataset = Dataset()
split_dict = dataset.get_split()
train, train_label = split_dict[TRAIN]
val, val_label = split_dict[VAL]

In [5]:
sess2items = dataset.get_sess2items()

In [78]:
max(sess2items.apply(lambda x: len(x)))

100

In [36]:
padded_sess = sess2items.apply(lambda x: np.array(x[-5:]) if len(x) >= 5 else np.pad(x, (5 - len(x), 0), constant_values=0))

In [37]:
padded_sess

session_id
3                        [0, 0, 0, 8122, 8122]
13                         [0, 0, 0, 0, 13198]
18                   [0, 0, 3377, 2085, 15459]
19            [21550, 3676, 15977, 5635, 6967]
24            [358, 15645, 8772, 23630, 15592]
                          ...                 
4439986    [11724, 11298, 16286, 10426, 23334]
4439990      [3379, 14419, 18651, 6596, 19035]
4439994                    [0, 0, 0, 0, 21387]
4439999       [11004, 1808, 7101, 1083, 13367]
4440001    [12039, 16481, 17238, 23434, 17271]
Name: item_id, Length: 1100000, dtype: object

In [42]:
aa=padded_sess.loc[[3,13]]

In [74]:
aa.values

array([array([   0,    0,    0, 8122, 8122]),
       array([    0,     0,     0,     0, 13198])], dtype=object)

In [73]:
np.stack(aa.values)

array([[    0,     0,     0,  8122,  8122],
       [    0,     0,     0,     0, 13198]])

In [56]:
aa.values[1].shape

(5,)

In [70]:
np.stack(aa.values).shape

(2, 5)

In [35]:
np.array(aa, dtype=np.float32)

ValueError: setting an array element with a sequence.

In [47]:
mapping_dict = dict(zip(sess2items.index.values, np.arange(len(sess2items.index.values))))

In [53]:
unique_val_id = val[SESS_ID].unique()

In [55]:
session_indices = [mapping_dict[s] for s in unique_val_id]

In [56]:
padded_sess[session_indices]

array([[16621,  8798, 14028, 16621, 14028],
       [    0,  1259, 21987, 10109,  1862],
       [    0,     0,     0,     0, 23461],
       ...,
       [    0,     0,     0,     0, 16602],
       [    0,     0,     0, 14708,  3308],
       [11724, 11298, 16286, 10426, 23334]])

In [5]:
sess2items

session_id
3                                               [8122, 8122]
13                                                   [13198]
18                                       [3377, 2085, 15459]
19         [16789, 23510, 10786, 21726, 5336, 19985, 7005...
24         [2456, 2456, 13541, 9827, 358, 15645, 8772, 23...
                                 ...                        
4439986           [19823, 11724, 11298, 16286, 10426, 23334]
4439990    [18651, 14709, 1156, 940, 3408, 21923, 3379, 1...
4439994                                              [21387]
4439999         [5045, 7161, 11004, 1808, 7101, 1083, 13367]
4440001    [21322, 21198, 2917, 23072, 21322, 21508, 1521...
Name: item_id, Length: 1100000, dtype: object

In [22]:
PADDING_LENGTH = 2
PADDING_IDX = 0

In [18]:
sess2items_array = sess2items.values

In [19]:
sample_1 = [1,2,3]
sample_2 = [4,5]


In [20]:
import numpy as np

In [26]:
dataset.get_train_sessions()

session_id  item_id                    date
0                 3     8122 2020-12-18 21:25:00.373
1                 3     8122 2020-12-18 21:19:48.093
2                13    13198 2020-03-13 19:35:27.136
3                18    15459 2020-08-26 19:18:30.833
4                18     2085 2020-08-26 19:16:31.211
...             ...      ...                     ...
4743815     4440001    17238 2020-10-30 23:37:20.658
4743816     4440001    11916 2020-10-30 23:31:56.607
4743817     4440001    12039 2020-10-30 23:36:17.934
4743818     4440001    23434 2020-10-30 23:39:55.186
4743819     4440001      249 2020-10-30 23:27:37.873

[4743820 rows x 3 columns]

In [33]:
dataset.get_train_purchases()

session_id  item_id                    date
0                3    12704 2020-12-18 21:26:47.986
1               13    15717 2020-03-13 19:36:15.507
2               18    21005 2020-08-26 19:20:32.049
3               19    10555 2020-11-02 17:16:45.920
4               24    11141 2020-02-26 18:27:44.114
...            ...      ...                     ...
999995     4439986     2445 2021-05-13 11:56:37.464
999996     4439990     7396 2020-08-22 14:28:22.382
999997     4439994    18255 2020-11-27 20:10:28.961
999998     4439999    14313 2020-11-27 11:01:41.356
999999     4440001    14028 2020-10-30 23:46:05.218

[1000000 rows x 3 columns]

In [43]:
len(dataset.get_sess2items().index.values)

1100000

In [25]:
sess2items_array

array([list([8122, 8122]), list([13198]), list([3377, 2085, 15459]), ...,
       list([21387]), list([5045, 7161, 11004, 1808, 7101, 1083, 13367]),
       list([21322, 21198, 2917, 23072, 21322, 21508, 15212, 5540, 22634, 8461, 249, 11916, 19656, 21972, 12039, 16481, 17238, 23434, 17271])],
      dtype=object)

In [35]:
padded_sess = np.array([s[-PADDING_LENGTH:] if len(s)>=PADDING_LENGTH else np.pad(s, (PADDING_LENGTH-len(s), 0)) for s in sess2items_array])

In [36]:
padded_sess[0]

array([8122, 8122])

In [31]:
CONTEXT_SIZE = 5

In [32]:
np.array([np.random.choice(s, size=CONTEXT_SIZE, replace=True) for s in sess2items_array])

array([[ 8122,  8122,  8122,  8122,  8122],
       [13198, 13198, 13198, 13198, 13198],
       [ 3377, 15459,  3377, 15459, 15459],
       ...,
       [21387, 21387, 21387, 21387, 21387],
       [13367, 11004, 11004,  7161,  7161],
       [ 5540, 21508, 22634, 22634, 11916]])

In [23]:
np.pad(sample_1, (0, PADDING_LENGTH-len(sample_1)))

ValueError: index can't contain negative values

In [ ]:
[s[-PADDING_LENGTH:] if len(s)>=5 for s in sess2items_array]

In [5]:
train_sess = dataset.get_train_sessions()

In [9]:
sorted_train_sess = train_sess.sort_values([SESS_ID, DATE])

In [10]:
for sess_id, item_id in zip(sorted_train_sess[SESS_ID], sorted_train_sess[ITEM_ID]):
    pass

session_id  item_id                    date
1                 3     8122 2020-12-18 21:19:48.093
0                 3     8122 2020-12-18 21:25:00.373
2                13    13198 2020-03-13 19:35:27.136
5                18     3377 2020-08-26 19:15:47.232
4                18     2085 2020-08-26 19:16:31.211
...             ...      ...                     ...
4743817     4440001    12039 2020-10-30 23:36:17.934
4743804     4440001    16481 2020-10-30 23:37:09.460
4743815     4440001    17238 2020-10-30 23:37:20.658
4743818     4440001    23434 2020-10-30 23:39:55.186
4743806     4440001    17271 2020-10-30 23:40:28.149

[4743820 rows x 3 columns]

In [3]:
dataset.get_sess2items()

session_id
3                                               [8122, 8122]
13                                                   [13198]
18                                       [15459, 2085, 3377]
19         [21726, 5336, 21550, 16911, 6978, 6967, 3676, ...
24         [2456, 9827, 2456, 23630, 358, 13541, 8772, 15...
                                 ...                        
4439986           [11724, 16286, 11298, 19823, 23334, 10426]
4439990    [1156, 18651, 6596, 14419, 940, 3379, 14709, 3...
4439994                                              [21387]
4439999         [11004, 7101, 1083, 1808, 5045, 7161, 13367]
4440001    [21322, 8461, 22634, 16481, 15212, 17271, 2132...
Name: item_id, Length: 1100000, dtype: object

In [ ]:
train_data = dataset.get_train_sessions()
lead_data = dataset.get_test_leaderboard_sessions()
test_data = dataset.get_test_final_sessions()
all_data = pd.concat([train_data, lead_data, test_data], axis=0)

In [75]:
import torch
import torch.nn.functional as F

In [9]:
a = torch.randn(10,256)

In [20]:
b = torch.randn(10)

In [32]:
b

tensor([ 0.1798, -0.1840,  0.1893,  0.2933,  0.6679,  0.3868, -0.4115, -0.9132,
         0.3307, -2.0031])

In [31]:
a/(b.view(10,1))

tensor([[ -5.3732,  -3.4286,  -0.0543,  ...,   5.2718,  15.1263,  -8.1657],
        [ -2.1946,   8.2952,  -7.0780,  ...,  -1.6626,  -5.5554,  -3.5762],
        [-11.1470,  -7.9578,   0.0642,  ...,   7.6214,  10.5466,  -7.7425],
        ...,
        [  2.2519,   0.8837,   0.4500,  ...,   1.4061,   0.6266,   1.1989],
        [ -1.9266,   1.2366,  -0.5472,  ...,   3.4262,   0.7491,   5.0360],
        [ -0.3896,  -0.0563,  -0.2915,  ...,  -0.6442,  -0.0820,  -0.3002]])

In [19]:
a/b

tensor([[-3.5417,  2.2443,  0.0208,  ...,  5.6584,  2.2434,  0.5422],
        [ 1.4802,  5.5562, -2.7767,  ...,  1.8261,  0.8431, -0.2430],
        [-7.7380,  5.4857, -0.0259,  ...,  8.6151,  1.6473,  0.5414],
        ...,
        [-7.5393,  2.9382,  0.8762,  ..., -7.6659, -0.4720,  0.4044],
        [-2.3360, -1.4890,  0.3859,  ...,  6.7648,  0.2044, -0.6151],
        [ 2.8609, -0.4107, -1.2452,  ...,  7.7040,  0.1355, -0.2221]])

In [17]:
emb = torch.nn.Embedding(num_embeddings = dataset._ITEMS_NUM+1, embedding_dim = 10, padding_idx=dataset._ITEMS_NUM)
emb(torch.LongTensor([dataset._ITEMS_NUM]))


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
rand1 = torch.rand((10, 2))
norm_rand1 = F.normalize(rand1)
rand2 = torch.rand((10, 2))
torch.einsum("bf,bf->b", rand1, rand2)

In [ ]:
norm_rand1

In [ ]:
rand1

In [ ]:
rand.view(1024,-1,64).shape

In [ ]:
prova = torch.Tensor(np.array([[1,2,3], [0,0,1]]))
prova

In [ ]:
prova.mean(dim=-1)

In [ ]:
den = (prova!=0).sum(dim=-1)
num = prova.sum(dim=-1)
num/den
# torch.nonzero(prova)
#mask = prova!=0
#prova*mask.sum(dim=-1)/mask.sum(dim=-1)

In [ ]:
emb = torch.nn.Embedding(4, 10, padding_idx=0)

In [ ]:
emb_tensor = emb.weight

In [ ]:
emb_tensor

In [ ]:
emb_tensor[torch.LongTensor([0,1])]

In [ ]:
torch.mean(emb(torch.LongTensor([0,1,2])))

In [ ]:
torch.mean(emb(torch.LongTensor([1,2])))

In [ ]:
a, b = train_label[[SESS_ID, ITEM_ID]].values[0]

In [ ]:
b

In [ ]:
train[[SESS_ID, ITEM_ID]].to_dict(orient="records")

In [ ]:
dataset = Dataset()

In [ ]:
item_features = dataset.get_item_features()

In [ ]:
item_features

In [ ]:
oh_cat = pd.get_dummies(item_features[F_CAT], prefix = "cat")

In [ ]:
oh_val = pd.get_dummies(item_features[F_VAL], prefix="val")

In [ ]:
item_features_oh = item_features.join(oh_cat).join(oh_val)

In [ ]:
item_features_oh = item_features_oh.groupby(ITEM_ID).sum()

In [ ]:
item_features_oh = item_features_oh.drop([F_VAL, F_CAT], axis=1).reset_index()

In [ ]:
item_features_oh